import test from 'node:test';
import assert from 'node:assert/strict';
import {validateMintedPackage,planMintedCollection,buildMintedMetadata} from '../src/minted.mjs';
const png='data:image/png;base64,aGVsbG8=';
function fixture(){return {schema:'minted.collection',version:1,artist:{id:'artist-1',name:'Artist'},collection:{id:'collection-1',name:'Owls'},character:{id:'owl-1',name:'Owl'},canvas:{width:100,height:100},layers:[{id:'body',name:'Body',role:'base',colorable:true,appearance:100,traits:[{id:'body-basic',name:'Basic',weight:1,image:png}]},{id:'hat',name:'Hat',role:'trait',colorable:true,appearance:50,traits:[{id:'hat-cap',name:'Cap',weight:1,image:png}]}]};}
test('metadata preserves IDs, original draw order and required Labs attribution',()=>{const p=fixture(),s=p.layers.map(layer=>({layer,trait:layer.traits[0]}));const m=buildMintedMetadata(p,s,1,'stencils/1.png');assert.equal(m.minted.artist_id,'artist-1');assert.deepEqual(m.minted.layers.map(l=>l.layer_id),['body','hat']);assert.deepEqual(m.attributes,[{trait_type:'Body',value:'Basic'},{trait_type:'Hat',value:'Cap'}]);assert.equal(m.minted.status,'uncolored');assert.equal(m.attribution,'Minted is a product of ALL THE MONEY Labs');});
test('unique stencil plan preserves exact layer appearance',()=>{const p=fixture();const tokens=planMintedCollection(p,2);assert.equal(tokens.filter(t=>t.some(s=>s.layer.id==='hat')).length,1);assert.equal(new Set(tokens.map(t=>t.map(s=>s.trait.id).join('|'))).size,2);assert.throws(()=>planMintedCollection(p,3),/more traits/);});
test('import rejects unknown schemas, duplicate IDs, remote images and missing base',()=>{for(const mutate of [p=>p.version=2,p=>p.layers[1].id='body',p=>p.layers[0].traits[0].image='https://example.com/art.png',p=>p.layers[0].appearance=50]){const p=fixture();mutate(p);assert.throws(()=>validateMintedPackage(p));}});
test('fixed effects must be last and presets must reference real traits',()=>{const p=fixture();p.layers[0].colorable=false;assert.throws(()=>validateMintedPackage(p));const q=fixture();q.stencils=[{index:1,traits:[{layer_id:'body',trait_id:'missing'}]}];assert.throws(()=>validateMintedPackage(q),/unknown/);q.stencils=[{index:1,traits:[{layer_id:'body',trait_id:'body-basic'}]}];assert.equal(validateMintedPackage(q),q);});
